
services:
  certifier_django:
    env_file: 
      - path: ../../.env
        required: true
    build:
      context: ../..
      dockerfile: ./docker/nonprod/Dockerfile
      args:
        - USER=${USER}
    volumes:
      - ../..:/backend
      - ${HOME}/.ssh:/home/${USER}/.ssh
    ports:
      - 8022:8000
      - 8033:8001
    container_name: certifier_server_nonprod
    networks:
      - db
    command: /bin/sh -c "while sleep 1000; do :; done"

networks:
  db:
    name: dev_db_network
    external: true